# Generated by Django 4.2.6 on 2023-10-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_bet', models.FloatField()),
                ('players_bang', models.FloatField()),
                ('players_profit', models.FloatField()),
                ('site_profit', models.FloatField()),
                ('crash_point', models.FloatField()),
                ('redbear', models.FloatField()),
                ('greenbull', models.FloatField()),
                ('site_historical_profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TextProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField()),
                ('processed', models.TextField()),
                ('redgreen', models.TextField()),
            ],
        ),
    ]
