# Generated by Django 4.2.6 on 2023-10-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcrash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_bet', models.CharField(max_length=100)),
                ('payout', models.CharField(max_length=10)),
                ('crashout', models.CharField(max_length=10)),
                ('players_loose', models.CharField(max_length=100)),
                ('players_profit', models.CharField(max_length=100)),
                ('site_profit', models.CharField(max_length=100)),
                ('site_profit_sigma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('payout', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=100)),
            ],
        ),
    ]
