# Generated by Django 4.2.6 on 2023-10-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcrash', '0003_gameanaylze'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameAnaylze',
            new_name='GameAnalyze',
        ),
    ]
