# Generated by Django 4.2.6 on 2023-10-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcrash', '0004_rename_gameanaylze_gameanalyze'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameAnalyze',
        ),
    ]
