# Generated by Django 4.2.6 on 2023-10-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcrash', '0005_delete_gameanalyze'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofit',
            name='site_peak_valley',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
