# Generated by Django 4.2.6 on 2023-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcrash', '0007_gameprofit_r_players_bet_gameprofit_r_players_loose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofit',
            name='moon_site_sigma',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
